#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# install nvidia cudnn library
#
DIB_NVIDIA_CUDNN_CUDA_HOME=${DIB_NVIDIA_CUDNN_CUDA_HOME:-/usr/local/cuda-9.1}
DIB_NVIDIA_CUDNN_LIBRARY=${DIB_NVIDIA_CUDNN_LIBRARY:-http://192.168.241.198/cudnn/v7.0.5-for-cuda9.1/cudnn-9.1-linux-x64-v7.tgz}
wget ${DIB_NVIDIA_CUDNN_LIBRARY}
tar -zxf $(basename ${DIB_NVIDIA_CUDNN_LIBRARY})
cp cuda/include/cudnn.h ${DIB_NVIDIA_CUDNN_CUDA_HOME}/include/
cp cuda/lib64/libcudnn* ${DIB_NVIDIA_CUDNN_CUDA_HOME}/lib64/
chmod a+r ${DIB_NVIDIA_CUDNN_CUDA_HOME}/include/cudnn.h
chmod a+r ${DIB_NVIDIA_CUDNN_CUDA_HOME}/lib64/libcudnn*
ln -sf ${DIB_NVIDIA_CUDNN_CUDA_HOME} /usr/local/cuda
rm -f $(basename ${DIB_NVIDIA_CUDNN_LIBRARY})
#
