#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# dummy code
pwd
ls $(dirname $0)

# install nvidia tesla k80 driver
#
# yum -y install dkms
# yum -y install kernel-devel kernel-headers
# wget http://192.168.241.198/drivers/nvidia-diag-driver-local-repo-rhel7-390.12-1.0-1.x86_64.rpm
# rpm -i nvidia-diag-driver-local-repo-rhel7-390.12-1.0-1.x86_64.rpm
# yum clean all
# yum -y install cuda-drivers
# reboot
#
# nvidia-smi
#

# patch cloud-init (hack CentOS-7-x86_64-GenericCloud.qcow2.xz.tgz)
#
# SRCDIR=$(dirname $0)
# install -D -g root -o root -m 0755 ${SRCDIR}/patch-cloudinit/cloud.cfg /etc/cloud/cloud.cfg
# install -D -g root -o root ${SRCDIR}/patch-cloudinit/cc_set_passwords.py /usr/lib/python2.7/site-packages/cloudinit/config/cc_set_passwords.py
#
# AS-IS
#
def handle(_name, cfg, cloud, log, args):
    if len(args) != 0:
        # if run from command line, and give args, wipe the chpasswd['list']
        password = args[0]
        if 'chpasswd' in cfg and 'list' in cfg['chpasswd']:
            del cfg['chpasswd']['list']
    else:
        password = util.get_cfg_option_str(cfg, "password", None)

    expire = True
    plist = None

    if 'chpasswd' in cfg:
        chfg = cfg['chpasswd']
        plist = util.get_cfg_option_str(chfg, 'list', plist)
        expire = util.get_cfg_option_bool(chfg, 'expire', expire)

    if not plist and password:
        (users, _groups) = ug_util.normalize_users_groups(cfg, cloud.distro)
        (user, _user_config) = ug_util.extract_default(users)
        if user:
            plist = "%s:%s" % (user, password)
        else:
            log.warn("No default or defined user to change password for.")
#
# TO-BE
#
def handle(_name, cfg, cloud, log, args):
    if len(args) != 0:
        # if run from command line, and give args, wipe the chpasswd['list']
        password = args[0]
        if 'chpasswd' in cfg and 'list' in cfg['chpasswd']:
            del cfg['chpasswd']['list']
    else:
        password = util.get_cfg_option_str(cfg, "password", None)

    # HACK :: use admin_pass key from metadata
    if not password:
        metadata = cloud.datasource.metadata
        if metadata and 'admin_pass' in metadata:
            password = metadata['admin_pass']

    expire = True
    plist = None

    if 'chpasswd' in cfg:
        chfg = cfg['chpasswd']
        plist = util.get_cfg_option_str(chfg, 'list', plist)
        expire = util.get_cfg_option_bool(chfg, 'expire', expire)

    if not plist and password:
        (users, _groups) = ug_util.normalize_users_groups(cfg, cloud.distro)
        (user, _user_config) = ug_util.extract_default(users)
        if user:
            plist = "%s:%s" % (user, password)
            # HACK :: change root's password
            plist = plist + "\nroot:%s" % password
        else:
            log.warn("No default or defined user to change password for.")
#
