#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# dummy code
pwd
ls $(dirname $0)

# install nvidia tesla k80 driver
#
# yum -y install dkms
# yum -y install kernel-devel kernel-headers
# wget http://192.168.241.198/drivers/nvidia-diag-driver-local-repo-rhel7-390.12-1.0-1.x86_64.rpm
# rpm -i nvidia-diag-driver-local-repo-rhel7-390.12-1.0-1.x86_64.rpm
# yum clean all
# yum -y install cuda-drivers
# reboot
#
# nvidia-smi
#

# patch cloud-init (hack CentOS-7-x86_64-GenericCloud.qcow2.xz.tgz)
#
# SRCDIR=$(dirname $0)
# install -D -g root -o root -m 0755 ${SRCDIR}/patch-cloudinit/cloud.cfg /etc/cloud/cloud.cfg
# install -D -g root -o root ${SRCDIR}/patch-cloudinit/cc_set_passwords.py /usr/lib/python2.7/site-packages/cloudinit/config/cc_set_passwords.py
#
# AS-IS
#
# def handle(_name, cfg, cloud, log, args):
#
# TO-BE
#
# def handle(_name, cfg, cloud, log, args):
# 
#    #use admin_pass key from metadata
#    if not password:
#        metadata = cloud.datasource.metadata
#        if metadata and 'admin_pass' in metadata:
#            password = metadata['admin_pass']
#
