#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# rebuild curl with openssl, without nss
#
yum -y groupinstall Development tools

wget https://www.openssl.org/source/openssl-1.0.2l.tar.gz
tar -xzvf openssl-1.0.2l.tar.gz
cd openssl-1.0.2l
./config --shared 
make && make install

wget https://curl.haxx.se/download/curl-7.55.1.tar.gz
tar -xzvf curl-7.55.1.tar.gz
cd curl-7.55.1
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/ssl/lib
./configure --prefix=/usr/local/curl/ --without-nss --with-ssl=/usr/local/ssl/
make && make install

ln -s /usr/local/curl/bin/curl /usr/bin/curl
curl --version
#
