#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# rebuild curl with openssl, without nss
#
yum -y groupinstall Development tools

curl -o openssl-1.0.2l.tar.gz  https://www.openssl.org/source/openssl-1.0.2l.tar.gz
tar -xzvf openssl-1.0.2l.tar.gz
cd openssl-1.0.2l
./config --shared 
make && make install

curl -o curl-7.55.1.tar.gz https://curl.haxx.se/download/curl-7.55.1.tar.gz
tar -xzvf curl-7.55.1.tar.gz
cd curl-7.55.1
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH:-}:/usr/local/ssl/lib
./configure --prefix=/usr/local/curl/ --without-nss --with-ssl=/usr/local/ssl/
make && make install

cp /usr/local/curl/bin/curl /usr/bin/curl
curl --version

# for login shell
#echo 'export LD_LIBRARY_PATH=${LD_LIBRARY_PATH:-}:/usr/local/ssl/lib' >> /etc/profile

# for non-login shell e.g. sudo su
#echo 'export LD_LIBRARY_PATH=${LD_LIBRARY_PATH:-}:/usr/local/ssl/lib' >> /root/.bashrc

echo '/usr/local/ssl/lib' > /etc/ld.so.conf.d/openssl.conf
ldconfig
#
