#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# install docker
#
yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
yum -y install docker-ce # latest version
#yum list docker-ce --showduplicates | sort -r
#yum install <FULLY-QUALIFIED-PACKAGE-NAME> # specific version
#
