#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# install nvidia cudnn library
#
wget http://192.168.241.198/cudnn/v7.0.5-for-cuda9.1/cudnn-9.1-linux-x64-v7.tgz
tar -zxf cudnn-9.1-linux-x64-v7.tgz
cp cuda/include/cudnn.h /usr/local/cuda-9.1/include/
cp cuda/lib64/libcudnn* /usr/local/cuda-9.1/lib64/
chmod a+r /usr/local/cuda-9.1/include/cudnn.h
chmod a+r /usr/local/cuda-9.1/lib64/libcudnn*
ln -sf /usr/local/cuda-9.1 /usr/local/cuda
rm -f cudnn-9.1-linux-x64-v7.tgz
#
