#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# install nvidia cuda toolkit
#
DIB_NVIDIA_CUDA_TOOLKIT=${DIB_NVIDIA_CUDA_TOOLKIT:-http://192.168.241.198/cuda-toolkit/9.1/cuda-repo-rhel7-9.1.85-1.x86_64.rpm}
wget ${DIB_NVIDIA_CUDA_TOOLKIT}
#rpm -i $(basename ${DIB_NVIDIA_CUDA_TOOLKIT})
#yum clean all
#yum -y install cuda
#rm -f $(basename ${DIB_NVIDIA_CUDA_TOOLKIT})
#
