#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# install nvidia cuda toolkit
#
wget http://192.168.241.198/cuda-toolkit/9.1/cuda-repo-rhel7-9.1.85-1.x86_64.rpm
rpm -i cuda-repo-rhel7-9.1.85-1.x86_64.rpm
yum clean all
yum -y install cuda
rm -f cuda-repo-rhel7-9.1.85-1.x86_64.rpm
#
